repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: ee6b38352380ce52369d16b7873093c4b8bf829b # frozen: v8.24.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: d9196b3a0a6fbc530f2bacea36c11a3b0214ff13 # frozen: v0.1.28
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck

  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: a804ee07a4c0c0793d3698a8936dea8d79116614 # frozen: v0.15.0
    hooks:
      - id: trivyfs-docker
        args: ["."]
      - id: trivyconfig-docker
        args: ["."]
  #  - repo: https://github.com/terraform-docs/terraform-docs
  #    rev: v0.16.0
  #    hooks:
  #      - id: terraform-docs-system
  #        args:
  #          [
  #            "markdown",
  #            "--output-file",
  #            "README.md",
  #            "--hide-empty",
  #            "--indent",
  #            "3",
  #            ".",
  #          ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "f12edd9c7be1c20cfa42420fd0e6df71e42b51ea" # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude_types:
          - markdown
      - id: prettier
        name: prettier markdown
        types:
          - markdown
        args: ["--prose-wrap", "always"]

  - repo: https://github.com/golangci/golangci-lint
    rev: 00a561d9a79578a2800dece2f04c60ad479a3798 # frozen: v2.1.2
    hooks:
      - id: golangci-lint
      - id: golangci-lint-full
        entry: bash -c 'cd test && golangci-lint run --fix'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 586c3ea3f51230da42bab657c6a32e9e66c364f0 # frozen: v0.44.0
    hooks:
      - id: markdownlint-fix-docker

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
